version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: SSHProxy-postgres
    environment:
      POSTGRES_USER: SSHProxy_user
      POSTGRES_PASSWORD: SSHProxy_password
      POSTGRES_DB: SSHProxy_db 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U SSHProxy_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: SSHProxy-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: