FROM node:20-alpine

# Install openssl because Prisma engine needs it to run on Alpine
RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
# For Prisma, it's often better to ensure all dependencies are clean
RUN npm install

COPY . .

# Generate the Prisma Client specifically for the Alpine environment
# This MUST happen before 'npm run build'
RUN npx prisma generate

RUN npm run build

EXPOSE 4000

CMD ["node", "dist/app.js"]